# Generated by Django 5.1.6 on 2025-02-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
