# Generated by Django 5.1.6 on 2025-03-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg', '0002_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
